# TODO: remove this
inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - default.yml

AllCops:
  TargetRubyVersion: 2.7

MethodLength:
  Description: "Avoid methods longer than 30 lines of code."
  Max: 30 # default is 10

HashSyntax:
  Enabled: false
